/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountWorkWorkItemModel } from './AccountWorkWorkItemModel';
import {
    AccountWorkWorkItemModelFromJSON,
    AccountWorkWorkItemModelFromJSONTyped,
    AccountWorkWorkItemModelToJSON,
    AccountWorkWorkItemModelToJSONTyped,
} from './AccountWorkWorkItemModel';

/**
 * 
 * @export
 * @interface AccountMyWorkResult
 */
export interface AccountMyWorkResult {
    /**
     * True, when length of WorkItemDetails is same as the limit
     * @type {boolean}
     * @memberof AccountMyWorkResult
     */
    querySizeLimitExceeded?: boolean;
    /**
     * WorkItem Details
     * @type {Array<AccountWorkWorkItemModel>}
     * @memberof AccountMyWorkResult
     */
    workItemDetails?: Array<AccountWorkWorkItemModel>;
}

/**
 * Check if a given object implements the AccountMyWorkResult interface.
 */
export function instanceOfAccountMyWorkResult(value: object): value is AccountMyWorkResult {
    return true;
}

export function AccountMyWorkResultFromJSON(json: any): AccountMyWorkResult {
    return AccountMyWorkResultFromJSONTyped(json, false);
}

export function AccountMyWorkResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountMyWorkResult {
    if (json == null) {
        return json;
    }
    return {
        
        'querySizeLimitExceeded': json['querySizeLimitExceeded'] == null ? undefined : json['querySizeLimitExceeded'],
        'workItemDetails': json['workItemDetails'] == null ? undefined : ((json['workItemDetails'] as Array<any>).map(AccountWorkWorkItemModelFromJSON)),
    };
}

export function AccountMyWorkResultToJSON(json: any): AccountMyWorkResult {
    return AccountMyWorkResultToJSONTyped(json, false);
}

export function AccountMyWorkResultToJSONTyped(value?: AccountMyWorkResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'querySizeLimitExceeded': value['querySizeLimitExceeded'],
        'workItemDetails': value['workItemDetails'] == null ? undefined : ((value['workItemDetails'] as Array<any>).map(AccountWorkWorkItemModelToJSON)),
    };
}

