/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents Recent Mention Work Item
 * @export
 * @interface AccountRecentMentionWorkItemModel
 */
export interface AccountRecentMentionWorkItemModel {
    /**
     * Assigned To
     * @type {string}
     * @memberof AccountRecentMentionWorkItemModel
     */
    assignedTo?: string;
    /**
     * Work Item Id
     * @type {number}
     * @memberof AccountRecentMentionWorkItemModel
     */
    id?: number;
    /**
     * Latest date that the user were mentioned
     * @type {Date}
     * @memberof AccountRecentMentionWorkItemModel
     */
    mentionedDateField?: Date;
    /**
     * State of the work item
     * @type {string}
     * @memberof AccountRecentMentionWorkItemModel
     */
    state?: string;
    /**
     * Team project the work item belongs to
     * @type {string}
     * @memberof AccountRecentMentionWorkItemModel
     */
    teamProject?: string;
    /**
     * Title of the work item
     * @type {string}
     * @memberof AccountRecentMentionWorkItemModel
     */
    title?: string;
    /**
     * Type of Work Item
     * @type {string}
     * @memberof AccountRecentMentionWorkItemModel
     */
    workItemType?: string;
}

/**
 * Check if a given object implements the AccountRecentMentionWorkItemModel interface.
 */
export function instanceOfAccountRecentMentionWorkItemModel(value: object): value is AccountRecentMentionWorkItemModel {
    return true;
}

export function AccountRecentMentionWorkItemModelFromJSON(json: any): AccountRecentMentionWorkItemModel {
    return AccountRecentMentionWorkItemModelFromJSONTyped(json, false);
}

export function AccountRecentMentionWorkItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRecentMentionWorkItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'assignedTo': json['assignedTo'] == null ? undefined : json['assignedTo'],
        'id': json['id'] == null ? undefined : json['id'],
        'mentionedDateField': json['mentionedDateField'] == null ? undefined : (new Date(json['mentionedDateField'])),
        'state': json['state'] == null ? undefined : json['state'],
        'teamProject': json['teamProject'] == null ? undefined : json['teamProject'],
        'title': json['title'] == null ? undefined : json['title'],
        'workItemType': json['workItemType'] == null ? undefined : json['workItemType'],
    };
}

export function AccountRecentMentionWorkItemModelToJSON(json: any): AccountRecentMentionWorkItemModel {
    return AccountRecentMentionWorkItemModelToJSONTyped(json, false);
}

export function AccountRecentMentionWorkItemModelToJSONTyped(value?: AccountRecentMentionWorkItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignedTo': value['assignedTo'],
        'id': value['id'],
        'mentionedDateField': value['mentionedDateField'] == null ? undefined : ((value['mentionedDateField']).toISOString()),
        'state': value['state'],
        'teamProject': value['teamProject'],
        'title': value['title'],
        'workItemType': value['workItemType'],
    };
}

