/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkItemReference } from './WorkItemReference';
import {
    WorkItemReferenceFromJSON,
    WorkItemReferenceFromJSONTyped,
    WorkItemReferenceToJSON,
    WorkItemReferenceToJSONTyped,
} from './WorkItemReference';

/**
 * Defines result of artifact URI query on work items. Contains mapping of work item IDs to artifact URI.
 * @export
 * @interface ArtifactUriQueryResult
 */
export interface ArtifactUriQueryResult {
    /**
     * A Dictionary that maps a list of work item references to the given list of artifact URI.
     * @type {{ [key: string]: Array<WorkItemReference>; }}
     * @memberof ArtifactUriQueryResult
     */
    artifactUrisQueryResult?: { [key: string]: Array<WorkItemReference>; };
}

/**
 * Check if a given object implements the ArtifactUriQueryResult interface.
 */
export function instanceOfArtifactUriQueryResult(value: object): value is ArtifactUriQueryResult {
    return true;
}

export function ArtifactUriQueryResultFromJSON(json: any): ArtifactUriQueryResult {
    return ArtifactUriQueryResultFromJSONTyped(json, false);
}

export function ArtifactUriQueryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtifactUriQueryResult {
    if (json == null) {
        return json;
    }
    return {
        
        'artifactUrisQueryResult': json['artifactUrisQueryResult'] == null ? undefined : json['artifactUrisQueryResult'],
    };
}

export function ArtifactUriQueryResultToJSON(json: any): ArtifactUriQueryResult {
    return ArtifactUriQueryResultToJSONTyped(json, false);
}

export function ArtifactUriQueryResultToJSONTyped(value?: ArtifactUriQueryResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artifactUrisQueryResult': value['artifactUrisQueryResult'],
    };
}

