/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a request to update a work item comment.
 * @export
 * @interface CommentUpdate
 */
export interface CommentUpdate {
    /**
     * The updated text of the comment.
     * @type {string}
     * @memberof CommentUpdate
     */
    text?: string;
}

/**
 * Check if a given object implements the CommentUpdate interface.
 */
export function instanceOfCommentUpdate(value: object): value is CommentUpdate {
    return true;
}

export function CommentUpdateFromJSON(json: any): CommentUpdate {
    return CommentUpdateFromJSONTyped(json, false);
}

export function CommentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function CommentUpdateToJSON(json: any): CommentUpdate {
    return CommentUpdateToJSONTyped(json, false);
}

export function CommentUpdateToJSONTyped(value?: CommentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

