/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdentityRef } from './IdentityRef';
import {
    IdentityRefFromJSON,
    IdentityRefFromJSONTyped,
    IdentityRefToJSON,
    IdentityRefToJSONTyped,
} from './IdentityRef';
import type { ReferenceLinks } from './ReferenceLinks';
import {
    ReferenceLinksFromJSON,
    ReferenceLinksFromJSONTyped,
    ReferenceLinksToJSON,
    ReferenceLinksToJSONTyped,
} from './ReferenceLinks';
import type { CommentMention } from './CommentMention';
import {
    CommentMentionFromJSON,
    CommentMentionFromJSONTyped,
    CommentMentionToJSON,
    CommentMentionToJSONTyped,
} from './CommentMention';
import type { CommentReaction } from './CommentReaction';
import {
    CommentReactionFromJSON,
    CommentReactionFromJSONTyped,
    CommentReactionToJSON,
    CommentReactionToJSONTyped,
} from './CommentReaction';

/**
 * Comment on a Work Item.
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {IdentityRef}
     * @memberof Comment
     */
    createdBy?: IdentityRef;
    /**
     * The creation date of the comment.
     * @type {Date}
     * @memberof Comment
     */
    createdDate?: Date;
    /**
     * Effective Date/time value for adding the comment. Can be optionally different from CreatedDate.
     * @type {Date}
     * @memberof Comment
     */
    createdOnBehalfDate?: Date;
    /**
     * 
     * @type {IdentityRef}
     * @memberof Comment
     */
    createdOnBehalfOf?: IdentityRef;
    /**
     * Represents the possible types for the comment format.
     * @type {string}
     * @memberof Comment
     */
    format?: CommentFormatEnum;
    /**
     * The id assigned to the comment.
     * @type {number}
     * @memberof Comment
     */
    id?: number;
    /**
     * Indicates if the comment has been deleted.
     * @type {boolean}
     * @memberof Comment
     */
    isDeleted?: boolean;
    /**
     * The mentions of the comment.
     * @type {Array<CommentMention>}
     * @memberof Comment
     */
    mentions?: Array<CommentMention>;
    /**
     * 
     * @type {IdentityRef}
     * @memberof Comment
     */
    modifiedBy?: IdentityRef;
    /**
     * The last modification date of the comment.
     * @type {Date}
     * @memberof Comment
     */
    modifiedDate?: Date;
    /**
     * The reactions of the comment.
     * @type {Array<CommentReaction>}
     * @memberof Comment
     */
    reactions?: Array<CommentReaction>;
    /**
     * The text of the comment in HTML format.
     * @type {string}
     * @memberof Comment
     */
    renderedText?: string;
    /**
     * The text of the comment.
     * @type {string}
     * @memberof Comment
     */
    text?: string;
    /**
     * The current version of the comment.
     * @type {number}
     * @memberof Comment
     */
    version?: number;
    /**
     * The id of the work item this comment belongs to.
     * @type {number}
     * @memberof Comment
     */
    workItemId?: number;
    /**
     * 
     * @type {ReferenceLinks}
     * @memberof Comment
     */
    links?: ReferenceLinks;
    /**
     * REST URL for the resource.
     * @type {string}
     * @memberof Comment
     */
    url?: string;
}


/**
 * @export
 */
export const CommentFormatEnum = {
    Markdown: 'markdown',
    Html: 'html'
} as const;
export type CommentFormatEnum = typeof CommentFormatEnum[keyof typeof CommentFormatEnum];


/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
    return true;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['createdBy'] == null ? undefined : IdentityRefFromJSON(json['createdBy']),
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'createdOnBehalfDate': json['createdOnBehalfDate'] == null ? undefined : (new Date(json['createdOnBehalfDate'])),
        'createdOnBehalfOf': json['createdOnBehalfOf'] == null ? undefined : IdentityRefFromJSON(json['createdOnBehalfOf']),
        'format': json['format'] == null ? undefined : json['format'],
        'id': json['id'] == null ? undefined : json['id'],
        'isDeleted': json['isDeleted'] == null ? undefined : json['isDeleted'],
        'mentions': json['mentions'] == null ? undefined : ((json['mentions'] as Array<any>).map(CommentMentionFromJSON)),
        'modifiedBy': json['modifiedBy'] == null ? undefined : IdentityRefFromJSON(json['modifiedBy']),
        'modifiedDate': json['modifiedDate'] == null ? undefined : (new Date(json['modifiedDate'])),
        'reactions': json['reactions'] == null ? undefined : ((json['reactions'] as Array<any>).map(CommentReactionFromJSON)),
        'renderedText': json['renderedText'] == null ? undefined : json['renderedText'],
        'text': json['text'] == null ? undefined : json['text'],
        'version': json['version'] == null ? undefined : json['version'],
        'workItemId': json['workItemId'] == null ? undefined : json['workItemId'],
        'links': json['_links'] == null ? undefined : ReferenceLinksFromJSON(json['_links']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function CommentToJSON(json: any): Comment {
    return CommentToJSONTyped(json, false);
}

export function CommentToJSONTyped(value?: Comment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdBy': IdentityRefToJSON(value['createdBy']),
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'createdOnBehalfDate': value['createdOnBehalfDate'] == null ? undefined : ((value['createdOnBehalfDate']).toISOString()),
        'createdOnBehalfOf': IdentityRefToJSON(value['createdOnBehalfOf']),
        'format': value['format'],
        'id': value['id'],
        'isDeleted': value['isDeleted'],
        'mentions': value['mentions'] == null ? undefined : ((value['mentions'] as Array<any>).map(CommentMentionToJSON)),
        'modifiedBy': IdentityRefToJSON(value['modifiedBy']),
        'modifiedDate': value['modifiedDate'] == null ? undefined : ((value['modifiedDate']).toISOString()),
        'reactions': value['reactions'] == null ? undefined : ((value['reactions'] as Array<any>).map(CommentReactionToJSON)),
        'renderedText': value['renderedText'],
        'text': value['text'],
        'version': value['version'],
        'workItemId': value['workItemId'],
        '_links': ReferenceLinksToJSON(value['links']),
        'url': value['url'],
    };
}

