/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a request to create a work item comment.
 * @export
 * @interface CommentCreate
 */
export interface CommentCreate {
    /**
     * The text of the comment.
     * @type {string}
     * @memberof CommentCreate
     */
    text?: string;
}

/**
 * Check if a given object implements the CommentCreate interface.
 */
export function instanceOfCommentCreate(value: object): value is CommentCreate {
    return true;
}

export function CommentCreateFromJSON(json: any): CommentCreate {
    return CommentCreateFromJSONTyped(json, false);
}

export function CommentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function CommentCreateToJSON(json: any): CommentCreate {
    return CommentCreateToJSONTyped(json, false);
}

export function CommentCreateToJSONTyped(value?: CommentCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

