/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailRecipients
 */
export interface EmailRecipients {
    /**
     * Plaintext email addresses.
     * @type {Array<string>}
     * @memberof EmailRecipients
     */
    emailAddresses?: Array<string>;
    /**
     * TfIds
     * @type {Array<string>}
     * @memberof EmailRecipients
     */
    tfIds?: Array<string>;
    /**
     * Unresolved entity ids
     * @type {Array<string>}
     * @memberof EmailRecipients
     */
    unresolvedEntityIds?: Array<string>;
}

/**
 * Check if a given object implements the EmailRecipients interface.
 */
export function instanceOfEmailRecipients(value: object): value is EmailRecipients {
    return true;
}

export function EmailRecipientsFromJSON(json: any): EmailRecipients {
    return EmailRecipientsFromJSONTyped(json, false);
}

export function EmailRecipientsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailRecipients {
    if (json == null) {
        return json;
    }
    return {
        
        'emailAddresses': json['emailAddresses'] == null ? undefined : json['emailAddresses'],
        'tfIds': json['tfIds'] == null ? undefined : json['tfIds'],
        'unresolvedEntityIds': json['unresolvedEntityIds'] == null ? undefined : json['unresolvedEntityIds'],
    };
}

export function EmailRecipientsToJSON(json: any): EmailRecipients {
    return EmailRecipientsToJSONTyped(json, false);
}

export function EmailRecipientsToJSONTyped(value?: EmailRecipients | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emailAddresses': value['emailAddresses'],
        'tfIds': value['tfIds'],
        'unresolvedEntityIds': value['unresolvedEntityIds'],
    };
}

