/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExternalPipeline } from './ExternalPipeline';
import {
    ExternalPipelineFromJSON,
    ExternalPipelineFromJSONTyped,
    ExternalPipelineToJSON,
    ExternalPipelineToJSONTyped,
} from './ExternalPipeline';
import type { ExternalEnvironment } from './ExternalEnvironment';
import {
    ExternalEnvironmentFromJSON,
    ExternalEnvironmentFromJSONTyped,
    ExternalEnvironmentToJSON,
    ExternalEnvironmentToJSONTyped,
} from './ExternalEnvironment';

/**
 * 
 * @export
 * @interface ExternalDeployment
 */
export interface ExternalDeployment {
    /**
     * 
     * @type {string}
     * @memberof ExternalDeployment
     */
    artifactId?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalDeployment
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalDeployment
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalDeployment
     */
    displayName?: string;
    /**
     * 
     * @type {ExternalEnvironment}
     * @memberof ExternalDeployment
     */
    environment?: ExternalEnvironment;
    /**
     * 
     * @type {string}
     * @memberof ExternalDeployment
     */
    group?: string;
    /**
     * 
     * @type {ExternalPipeline}
     * @memberof ExternalDeployment
     */
    pipeline?: ExternalPipeline;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExternalDeployment
     */
    relatedWorkItemIds?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof ExternalDeployment
     */
    runId?: number;
    /**
     * 
     * @type {number}
     * @memberof ExternalDeployment
     */
    sequenceNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof ExternalDeployment
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExternalDeployment
     */
    statusDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ExternalDeployment
     */
    url?: string;
}

/**
 * Check if a given object implements the ExternalDeployment interface.
 */
export function instanceOfExternalDeployment(value: object): value is ExternalDeployment {
    return true;
}

export function ExternalDeploymentFromJSON(json: any): ExternalDeployment {
    return ExternalDeploymentFromJSONTyped(json, false);
}

export function ExternalDeploymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalDeployment {
    if (json == null) {
        return json;
    }
    return {
        
        'artifactId': json['artifactId'] == null ? undefined : json['artifactId'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'description': json['description'] == null ? undefined : json['description'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'environment': json['environment'] == null ? undefined : ExternalEnvironmentFromJSON(json['environment']),
        'group': json['group'] == null ? undefined : json['group'],
        'pipeline': json['pipeline'] == null ? undefined : ExternalPipelineFromJSON(json['pipeline']),
        'relatedWorkItemIds': json['relatedWorkItemIds'] == null ? undefined : json['relatedWorkItemIds'],
        'runId': json['runId'] == null ? undefined : json['runId'],
        'sequenceNumber': json['sequenceNumber'] == null ? undefined : json['sequenceNumber'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusDate': json['statusDate'] == null ? undefined : (new Date(json['statusDate'])),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ExternalDeploymentToJSON(json: any): ExternalDeployment {
    return ExternalDeploymentToJSONTyped(json, false);
}

export function ExternalDeploymentToJSONTyped(value?: ExternalDeployment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artifactId': value['artifactId'],
        'createdBy': value['createdBy'],
        'description': value['description'],
        'displayName': value['displayName'],
        'environment': ExternalEnvironmentToJSON(value['environment']),
        'group': value['group'],
        'pipeline': ExternalPipelineToJSON(value['pipeline']),
        'relatedWorkItemIds': value['relatedWorkItemIds'],
        'runId': value['runId'],
        'sequenceNumber': value['sequenceNumber'],
        'status': value['status'],
        'statusDate': value['statusDate'] == null ? undefined : ((value['statusDate']).toISOString()),
        'url': value['url'],
    };
}

