/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalEnvironment
 */
export interface ExternalEnvironment {
    /**
     * 
     * @type {string}
     * @memberof ExternalEnvironment
     */
    displayName?: string;
    /**
     * 
     * @type {number}
     * @memberof ExternalEnvironment
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExternalEnvironment
     */
    type?: string;
}

/**
 * Check if a given object implements the ExternalEnvironment interface.
 */
export function instanceOfExternalEnvironment(value: object): value is ExternalEnvironment {
    return true;
}

export function ExternalEnvironmentFromJSON(json: any): ExternalEnvironment {
    return ExternalEnvironmentFromJSONTyped(json, false);
}

export function ExternalEnvironmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalEnvironment {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ExternalEnvironmentToJSON(json: any): ExternalEnvironment {
    return ExternalEnvironmentToJSONTyped(json, false);
}

export function ExternalEnvironmentToJSONTyped(value?: ExternalEnvironment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
        'id': value['id'],
        'type': value['type'],
    };
}

