/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes an update request for a work item field.
 * @export
 * @interface FieldUpdate
 */
export interface FieldUpdate {
    /**
     * Indicates whether the user wants to restore the field.
     * @type {boolean}
     * @memberof FieldUpdate
     */
    isDeleted?: boolean;
    /**
     * Indicates whether the user wants to lock the field.
     * @type {boolean}
     * @memberof FieldUpdate
     */
    isLocked?: boolean;
}

/**
 * Check if a given object implements the FieldUpdate interface.
 */
export function instanceOfFieldUpdate(value: object): value is FieldUpdate {
    return true;
}

export function FieldUpdateFromJSON(json: any): FieldUpdate {
    return FieldUpdateFromJSONTyped(json, false);
}

export function FieldUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'isDeleted': json['isDeleted'] == null ? undefined : json['isDeleted'],
        'isLocked': json['isLocked'] == null ? undefined : json['isLocked'],
    };
}

export function FieldUpdateToJSON(json: any): FieldUpdate {
    return FieldUpdateToJSONTyped(json, false);
}

export function FieldUpdateToJSONTyped(value?: FieldUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isDeleted': value['isDeleted'],
        'isLocked': value['isLocked'],
    };
}

