/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceLinks } from './ReferenceLinks';
import {
    ReferenceLinksFromJSON,
    ReferenceLinksFromJSONTyped,
    ReferenceLinksToJSON,
    ReferenceLinksToJSONTyped,
} from './ReferenceLinks';

/**
 * Describes a reference to an identity.
 * @export
 * @interface IdentityReference
 */
export interface IdentityReference {
    /**
     * Gets or sets the identifier of the identity.
     * @type {string}
     * @memberof IdentityReference
     */
    id?: string;
    /**
     * Legacy back-compat property. This has been the WIT specific value from Constants. Will be hidden (but exists) on the client unless they are targeting the newest version
     * @type {string}
     * @memberof IdentityReference
     */
    name?: string;
    /**
     * Deprecated - Can be retrieved by querying the Graph user referenced in the "self" entry of the IdentityRef "_links" dictionary
     * @type {string}
     * @memberof IdentityReference
     */
    directoryAlias?: string;
    /**
     * Deprecated - Available in the "avatar" entry of the IdentityRef "_links" dictionary
     * @type {string}
     * @memberof IdentityReference
     */
    imageUrl?: string;
    /**
     * Deprecated - Can be retrieved by querying the Graph membership state referenced in the "membershipState" entry of the GraphUser "_links" dictionary
     * @type {boolean}
     * @memberof IdentityReference
     */
    inactive?: boolean;
    /**
     * Deprecated - Can be inferred from the subject type of the descriptor (Descriptor.IsAadUserType/Descriptor.IsAadGroupType)
     * @type {boolean}
     * @memberof IdentityReference
     */
    isAadIdentity?: boolean;
    /**
     * Deprecated - Can be inferred from the subject type of the descriptor (Descriptor.IsGroupType)
     * @type {boolean}
     * @memberof IdentityReference
     */
    isContainer?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityReference
     */
    isDeletedInOrigin?: boolean;
    /**
     * Deprecated - not in use in most preexisting implementations of ToIdentityRef
     * @type {string}
     * @memberof IdentityReference
     */
    profileUrl?: string;
    /**
     * Deprecated - use Domain+PrincipalName instead
     * @type {string}
     * @memberof IdentityReference
     */
    uniqueName?: string;
    /**
     * 
     * @type {ReferenceLinks}
     * @memberof IdentityReference
     */
    links?: ReferenceLinks;
    /**
     * The descriptor is the primary way to reference the graph subject while the system is running. This field will uniquely identify the same graph subject across both Accounts and Organizations.
     * @type {string}
     * @memberof IdentityReference
     */
    descriptor?: string;
    /**
     * This is the non-unique display name of the graph subject. To change this field, you must alter its value in the source provider.
     * @type {string}
     * @memberof IdentityReference
     */
    displayName?: string;
    /**
     * This url is the full route to the source resource of this graph subject.
     * @type {string}
     * @memberof IdentityReference
     */
    url?: string;
}

/**
 * Check if a given object implements the IdentityReference interface.
 */
export function instanceOfIdentityReference(value: object): value is IdentityReference {
    return true;
}

export function IdentityReferenceFromJSON(json: any): IdentityReference {
    return IdentityReferenceFromJSONTyped(json, false);
}

export function IdentityReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'directoryAlias': json['directoryAlias'] == null ? undefined : json['directoryAlias'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'inactive': json['inactive'] == null ? undefined : json['inactive'],
        'isAadIdentity': json['isAadIdentity'] == null ? undefined : json['isAadIdentity'],
        'isContainer': json['isContainer'] == null ? undefined : json['isContainer'],
        'isDeletedInOrigin': json['isDeletedInOrigin'] == null ? undefined : json['isDeletedInOrigin'],
        'profileUrl': json['profileUrl'] == null ? undefined : json['profileUrl'],
        'uniqueName': json['uniqueName'] == null ? undefined : json['uniqueName'],
        'links': json['_links'] == null ? undefined : ReferenceLinksFromJSON(json['_links']),
        'descriptor': json['descriptor'] == null ? undefined : json['descriptor'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function IdentityReferenceToJSON(json: any): IdentityReference {
    return IdentityReferenceToJSONTyped(json, false);
}

export function IdentityReferenceToJSONTyped(value?: IdentityReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'directoryAlias': value['directoryAlias'],
        'imageUrl': value['imageUrl'],
        'inactive': value['inactive'],
        'isAadIdentity': value['isAadIdentity'],
        'isContainer': value['isContainer'],
        'isDeletedInOrigin': value['isDeletedInOrigin'],
        'profileUrl': value['profileUrl'],
        'uniqueName': value['uniqueName'],
        '_links': ReferenceLinksToJSON(value['links']),
        'descriptor': value['descriptor'],
        'displayName': value['displayName'],
        'url': value['url'],
    };
}

