/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Link description.
 * @export
 * @interface Link
 */
export interface Link {
    /**
     * Collection of link attributes.
     * @type {{ [key: string]: object; }}
     * @memberof Link
     */
    attributes?: { [key: string]: object; };
    /**
     * Relation type.
     * @type {string}
     * @memberof Link
     */
    rel?: string;
    /**
     * Link url.
     * @type {string}
     * @memberof Link
     */
    url?: string;
}

/**
 * Check if a given object implements the Link interface.
 */
export function instanceOfLink(value: object): value is Link {
    return true;
}

export function LinkFromJSON(json: any): Link {
    return LinkFromJSONTyped(json, false);
}

export function LinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Link {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'rel': json['rel'] == null ? undefined : json['rel'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function LinkToJSON(json: any): Link {
    return LinkToJSONTyped(json, false);
}

export function LinkToJSONTyped(value?: Link | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'],
        'rel': value['rel'],
        'url': value['url'],
    };
}

