/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Stores project ID and its process ID.
 * @export
 * @interface ProcessMigrationResultModel
 */
export interface ProcessMigrationResultModel {
    /**
     * The ID of the process.
     * @type {string}
     * @memberof ProcessMigrationResultModel
     */
    processId?: string;
    /**
     * The ID of the project.
     * @type {string}
     * @memberof ProcessMigrationResultModel
     */
    projectId?: string;
}

/**
 * Check if a given object implements the ProcessMigrationResultModel interface.
 */
export function instanceOfProcessMigrationResultModel(value: object): value is ProcessMigrationResultModel {
    return true;
}

export function ProcessMigrationResultModelFromJSON(json: any): ProcessMigrationResultModel {
    return ProcessMigrationResultModelFromJSONTyped(json, false);
}

export function ProcessMigrationResultModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessMigrationResultModel {
    if (json == null) {
        return json;
    }
    return {
        
        'processId': json['processId'] == null ? undefined : json['processId'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
    };
}

export function ProcessMigrationResultModelToJSON(json: any): ProcessMigrationResultModel {
    return ProcessMigrationResultModelToJSONTyped(json, false);
}

export function ProcessMigrationResultModelToJSONTyped(value?: ProcessMigrationResultModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'processId': value['processId'],
        'projectId': value['projectId'],
    };
}

