/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The class to represent a collection of REST reference links.
 * @export
 * @interface ReferenceLinks
 */
export interface ReferenceLinks {
    /**
     * The readonly view of the links.  Because Reference links are readonly, we only want to expose them as read only.
     * @type {{ [key: string]: object; }}
     * @memberof ReferenceLinks
     */
    links?: { [key: string]: object; };
}

/**
 * Check if a given object implements the ReferenceLinks interface.
 */
export function instanceOfReferenceLinks(value: object): value is ReferenceLinks {
    return true;
}

export function ReferenceLinksFromJSON(json: any): ReferenceLinks {
    return ReferenceLinksFromJSONTyped(json, false);
}

export function ReferenceLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : json['links'],
    };
}

export function ReferenceLinksToJSON(json: any): ReferenceLinks {
    return ReferenceLinksToJSONTyped(json, false);
}

export function ReferenceLinksToJSONTyped(value?: ReferenceLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': value['links'],
    };
}

