/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The Team Context for an operation.
 * @export
 * @interface TeamContext
 */
export interface TeamContext {
    /**
     * The team project Id or name.  Ignored if ProjectId is set.
     * @type {string}
     * @memberof TeamContext
     */
    project?: string;
    /**
     * The Team Project ID.  Required if Project is not set.
     * @type {string}
     * @memberof TeamContext
     */
    projectId?: string;
    /**
     * The Team Id or name.  Ignored if TeamId is set.
     * @type {string}
     * @memberof TeamContext
     */
    team?: string;
    /**
     * The Team Id
     * @type {string}
     * @memberof TeamContext
     */
    teamId?: string;
}

/**
 * Check if a given object implements the TeamContext interface.
 */
export function instanceOfTeamContext(value: object): value is TeamContext {
    return true;
}

export function TeamContextFromJSON(json: any): TeamContext {
    return TeamContextFromJSONTyped(json, false);
}

export function TeamContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamContext {
    if (json == null) {
        return json;
    }
    return {
        
        'project': json['project'] == null ? undefined : json['project'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'team': json['team'] == null ? undefined : json['team'],
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
    };
}

export function TeamContextToJSON(json: any): TeamContext {
    return TeamContextToJSONTyped(json, false);
}

export function TeamContextToJSONTyped(value?: TeamContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project': value['project'],
        'projectId': value['projectId'],
        'team': value['team'],
        'teamId': value['teamId'],
    };
}

