/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The result of a temporary query creation.
 * @export
 * @interface TemporaryQueryResponseModel
 */
export interface TemporaryQueryResponseModel {
    /**
     * The id of the temporary query item.
     * @type {string}
     * @memberof TemporaryQueryResponseModel
     */
    id?: string;
}

/**
 * Check if a given object implements the TemporaryQueryResponseModel interface.
 */
export function instanceOfTemporaryQueryResponseModel(value: object): value is TemporaryQueryResponseModel {
    return true;
}

export function TemporaryQueryResponseModelFromJSON(json: any): TemporaryQueryResponseModel {
    return TemporaryQueryResponseModelFromJSONTyped(json, false);
}

export function TemporaryQueryResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemporaryQueryResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TemporaryQueryResponseModelToJSON(json: any): TemporaryQueryResponseModel {
    return TemporaryQueryResponseModelToJSONTyped(json, false);
}

export function TemporaryQueryResponseModelToJSONTyped(value?: TemporaryQueryResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

