/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VssJsonCollectionWrapperBase
 */
export interface VssJsonCollectionWrapperBase {
    /**
     * The number of serialized items.
     * @type {number}
     * @memberof VssJsonCollectionWrapperBase
     */
    count?: number;
}

/**
 * Check if a given object implements the VssJsonCollectionWrapperBase interface.
 */
export function instanceOfVssJsonCollectionWrapperBase(value: object): value is VssJsonCollectionWrapperBase {
    return true;
}

export function VssJsonCollectionWrapperBaseFromJSON(json: any): VssJsonCollectionWrapperBase {
    return VssJsonCollectionWrapperBaseFromJSONTyped(json, false);
}

export function VssJsonCollectionWrapperBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VssJsonCollectionWrapperBase {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function VssJsonCollectionWrapperBaseToJSON(json: any): VssJsonCollectionWrapperBase {
    return VssJsonCollectionWrapperBaseToJSONTyped(json, false);
}

export function VssJsonCollectionWrapperBaseToJSONTyped(value?: VssJsonCollectionWrapperBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

