/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * This class is used to serialize collections as a single JSON object on the wire.
 * @export
 * @interface VssJsonCollectionWrapper
 */
export interface VssJsonCollectionWrapper {
    /**
     * The serialized item.
     * @type {string}
     * @memberof VssJsonCollectionWrapper
     */
    value?: string;
    /**
     * The number of serialized items.
     * @type {number}
     * @memberof VssJsonCollectionWrapper
     */
    count?: number;
}

/**
 * Check if a given object implements the VssJsonCollectionWrapper interface.
 */
export function instanceOfVssJsonCollectionWrapper(value: object): value is VssJsonCollectionWrapper {
    return true;
}

export function VssJsonCollectionWrapperFromJSON(json: any): VssJsonCollectionWrapper {
    return VssJsonCollectionWrapperFromJSONTyped(json, false);
}

export function VssJsonCollectionWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): VssJsonCollectionWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function VssJsonCollectionWrapperToJSON(json: any): VssJsonCollectionWrapper {
    return VssJsonCollectionWrapperToJSONTyped(json, false);
}

export function VssJsonCollectionWrapperToJSONTyped(value?: VssJsonCollectionWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'count': value['count'],
    };
}

