/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A WIQL query
 * @export
 * @interface Wiql
 */
export interface Wiql {
    /**
     * The text of the WIQL query
     * @type {string}
     * @memberof Wiql
     */
    query?: string;
}

/**
 * Check if a given object implements the Wiql interface.
 */
export function instanceOfWiql(value: object): value is Wiql {
    return true;
}

export function WiqlFromJSON(json: any): Wiql {
    return WiqlFromJSONTyped(json, false);
}

export function WiqlFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wiql {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function WiqlToJSON(json: any): Wiql {
    return WiqlToJSONTyped(json, false);
}

export function WiqlToJSONTyped(value?: Wiql | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
    };
}

