/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes a request to get a set of work items
 * @export
 * @interface WorkItemBatchGetRequest
 */
export interface WorkItemBatchGetRequest {
    /**
     * The expand parameters for work item attributes. Possible options are { None, Relations, Fields, Links, All }
     * @type {string}
     * @memberof WorkItemBatchGetRequest
     */
    $expand?: WorkItemBatchGetRequestExpandEnum;
    /**
     * AsOf UTC date time string
     * @type {Date}
     * @memberof WorkItemBatchGetRequest
     */
    asOf?: Date;
    /**
     * The flag to control error policy in a bulk get work items request. Possible options are {Fail, Omit}.
     * @type {string}
     * @memberof WorkItemBatchGetRequest
     */
    errorPolicy?: WorkItemBatchGetRequestErrorPolicyEnum;
    /**
     * The requested fields
     * @type {Array<string>}
     * @memberof WorkItemBatchGetRequest
     */
    fields?: Array<string>;
    /**
     * The requested work item ids
     * @type {Array<number>}
     * @memberof WorkItemBatchGetRequest
     */
    ids?: Array<number>;
}


/**
 * @export
 */
export const WorkItemBatchGetRequestExpandEnum = {
    None: 'none',
    Relations: 'relations',
    Fields: 'fields',
    Links: 'links',
    All: 'all'
} as const;
export type WorkItemBatchGetRequestExpandEnum = typeof WorkItemBatchGetRequestExpandEnum[keyof typeof WorkItemBatchGetRequestExpandEnum];

/**
 * @export
 */
export const WorkItemBatchGetRequestErrorPolicyEnum = {
    Fail: 'fail',
    Omit: 'omit'
} as const;
export type WorkItemBatchGetRequestErrorPolicyEnum = typeof WorkItemBatchGetRequestErrorPolicyEnum[keyof typeof WorkItemBatchGetRequestErrorPolicyEnum];


/**
 * Check if a given object implements the WorkItemBatchGetRequest interface.
 */
export function instanceOfWorkItemBatchGetRequest(value: object): value is WorkItemBatchGetRequest {
    return true;
}

export function WorkItemBatchGetRequestFromJSON(json: any): WorkItemBatchGetRequest {
    return WorkItemBatchGetRequestFromJSONTyped(json, false);
}

export function WorkItemBatchGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemBatchGetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '$expand': json['$expand'] == null ? undefined : json['$expand'],
        'asOf': json['asOf'] == null ? undefined : (new Date(json['asOf'])),
        'errorPolicy': json['errorPolicy'] == null ? undefined : json['errorPolicy'],
        'fields': json['fields'] == null ? undefined : json['fields'],
        'ids': json['ids'] == null ? undefined : json['ids'],
    };
}

export function WorkItemBatchGetRequestToJSON(json: any): WorkItemBatchGetRequest {
    return WorkItemBatchGetRequestToJSONTyped(json, false);
}

export function WorkItemBatchGetRequestToJSONTyped(value?: WorkItemBatchGetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '$expand': value['$expand'],
        'asOf': value['asOf'] == null ? undefined : ((value['asOf']).toISOString()),
        'errorPolicy': value['errorPolicy'],
        'fields': value['fields'],
        'ids': value['ids'],
    };
}

