/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Base class for work item tracking resource references.
 * @export
 * @interface WorkItemTrackingResourceReference
 */
export interface WorkItemTrackingResourceReference {
    /**
     * REST URL for the resource.
     * @type {string}
     * @memberof WorkItemTrackingResourceReference
     */
    url?: string;
}

/**
 * Check if a given object implements the WorkItemTrackingResourceReference interface.
 */
export function instanceOfWorkItemTrackingResourceReference(value: object): value is WorkItemTrackingResourceReference {
    return true;
}

export function WorkItemTrackingResourceReferenceFromJSON(json: any): WorkItemTrackingResourceReference {
    return WorkItemTrackingResourceReferenceFromJSONTyped(json, false);
}

export function WorkItemTrackingResourceReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemTrackingResourceReference {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function WorkItemTrackingResourceReferenceToJSON(json: any): WorkItemTrackingResourceReference {
    return WorkItemTrackingResourceReferenceToJSONTyped(json, false);
}

export function WorkItemTrackingResourceReferenceToJSONTyped(value?: WorkItemTrackingResourceReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

