/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Work item type state name, color and state category
 * @export
 * @interface WorkItemStateColor
 */
export interface WorkItemStateColor {
    /**
     * Category of state
     * @type {string}
     * @memberof WorkItemStateColor
     */
    category?: string;
    /**
     * Color value
     * @type {string}
     * @memberof WorkItemStateColor
     */
    color?: string;
    /**
     * Work item type state name
     * @type {string}
     * @memberof WorkItemStateColor
     */
    name?: string;
}

/**
 * Check if a given object implements the WorkItemStateColor interface.
 */
export function instanceOfWorkItemStateColor(value: object): value is WorkItemStateColor {
    return true;
}

export function WorkItemStateColorFromJSON(json: any): WorkItemStateColor {
    return WorkItemStateColorFromJSONTyped(json, false);
}

export function WorkItemStateColorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemStateColor {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'color': json['color'] == null ? undefined : json['color'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function WorkItemStateColorToJSON(json: any): WorkItemStateColor {
    return WorkItemStateColorToJSONTyped(json, false);
}

export function WorkItemStateColorToJSONTyped(value?: WorkItemStateColor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'color': value['color'],
        'name': value['name'],
    };
}

