/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Shallow Reference to a deleted work item.
 * @export
 * @interface WorkItemDeleteShallowReference
 */
export interface WorkItemDeleteShallowReference {
    /**
     * Work item ID.
     * @type {number}
     * @memberof WorkItemDeleteShallowReference
     */
    id?: number;
    /**
     * REST API URL of the resource
     * @type {string}
     * @memberof WorkItemDeleteShallowReference
     */
    url?: string;
}

/**
 * Check if a given object implements the WorkItemDeleteShallowReference interface.
 */
export function instanceOfWorkItemDeleteShallowReference(value: object): value is WorkItemDeleteShallowReference {
    return true;
}

export function WorkItemDeleteShallowReferenceFromJSON(json: any): WorkItemDeleteShallowReference {
    return WorkItemDeleteShallowReferenceFromJSONTyped(json, false);
}

export function WorkItemDeleteShallowReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemDeleteShallowReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function WorkItemDeleteShallowReferenceToJSON(json: any): WorkItemDeleteShallowReference {
    return WorkItemDeleteShallowReferenceToJSONTyped(json, false);
}

export function WorkItemDeleteShallowReferenceToJSONTyped(value?: WorkItemDeleteShallowReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
    };
}

