/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes the next state for a work item.
 * @export
 * @interface WorkItemNextStateOnTransition
 */
export interface WorkItemNextStateOnTransition {
    /**
     * Error code if there is no next state transition possible.
     * @type {string}
     * @memberof WorkItemNextStateOnTransition
     */
    errorCode?: string;
    /**
     * Work item ID.
     * @type {number}
     * @memberof WorkItemNextStateOnTransition
     */
    id?: number;
    /**
     * Error message if there is no next state transition possible.
     * @type {string}
     * @memberof WorkItemNextStateOnTransition
     */
    message?: string;
    /**
     * Name of the next state on transition.
     * @type {string}
     * @memberof WorkItemNextStateOnTransition
     */
    stateOnTransition?: string;
}

/**
 * Check if a given object implements the WorkItemNextStateOnTransition interface.
 */
export function instanceOfWorkItemNextStateOnTransition(value: object): value is WorkItemNextStateOnTransition {
    return true;
}

export function WorkItemNextStateOnTransitionFromJSON(json: any): WorkItemNextStateOnTransition {
    return WorkItemNextStateOnTransitionFromJSONTyped(json, false);
}

export function WorkItemNextStateOnTransitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemNextStateOnTransition {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'id': json['id'] == null ? undefined : json['id'],
        'message': json['message'] == null ? undefined : json['message'],
        'stateOnTransition': json['stateOnTransition'] == null ? undefined : json['stateOnTransition'],
    };
}

export function WorkItemNextStateOnTransitionToJSON(json: any): WorkItemNextStateOnTransition {
    return WorkItemNextStateOnTransitionToJSONTyped(json, false);
}

export function WorkItemNextStateOnTransitionToJSONTyped(value?: WorkItemNextStateOnTransition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': value['errorCode'],
        'id': value['id'],
        'message': value['message'],
        'stateOnTransition': value['stateOnTransition'],
    };
}

