/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes an update request for a deleted work item.
 * @export
 * @interface WorkItemDeleteUpdate
 */
export interface WorkItemDeleteUpdate {
    /**
     * Sets a value indicating whether this work item is deleted.
     * @type {boolean}
     * @memberof WorkItemDeleteUpdate
     */
    isDeleted?: boolean;
}

/**
 * Check if a given object implements the WorkItemDeleteUpdate interface.
 */
export function instanceOfWorkItemDeleteUpdate(value: object): value is WorkItemDeleteUpdate {
    return true;
}

export function WorkItemDeleteUpdateFromJSON(json: any): WorkItemDeleteUpdate {
    return WorkItemDeleteUpdateFromJSONTyped(json, false);
}

export function WorkItemDeleteUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemDeleteUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'isDeleted': json['isDeleted'] == null ? undefined : json['isDeleted'],
    };
}

export function WorkItemDeleteUpdateToJSON(json: any): WorkItemDeleteUpdate {
    return WorkItemDeleteUpdateToJSONTyped(json, false);
}

export function WorkItemDeleteUpdateToJSONTyped(value?: WorkItemDeleteUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isDeleted': value['isDeleted'],
    };
}

