/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes a update work item type template request body.
 * @export
 * @interface WorkItemTypeTemplateUpdateModel
 */
export interface WorkItemTypeTemplateUpdateModel {
    /**
     * Describes the type of the action for the update request.
     * @type {string}
     * @memberof WorkItemTypeTemplateUpdateModel
     */
    actionType?: WorkItemTypeTemplateUpdateModelActionTypeEnum;
    /**
     * Methodology to which the template belongs, eg. Agile, Scrum, CMMI.
     * @type {string}
     * @memberof WorkItemTypeTemplateUpdateModel
     */
    methodology?: string;
    /**
     * String representation of the work item type template.
     * @type {string}
     * @memberof WorkItemTypeTemplateUpdateModel
     */
    template?: string;
    /**
     * The type of the template described in the request body.
     * @type {string}
     * @memberof WorkItemTypeTemplateUpdateModel
     */
    templateType?: WorkItemTypeTemplateUpdateModelTemplateTypeEnum;
}


/**
 * @export
 */
export const WorkItemTypeTemplateUpdateModelActionTypeEnum = {
    Import: 'import',
    Validate: 'validate'
} as const;
export type WorkItemTypeTemplateUpdateModelActionTypeEnum = typeof WorkItemTypeTemplateUpdateModelActionTypeEnum[keyof typeof WorkItemTypeTemplateUpdateModelActionTypeEnum];

/**
 * @export
 */
export const WorkItemTypeTemplateUpdateModelTemplateTypeEnum = {
    WorkItemType: 'workItemType',
    GlobalWorkflow: 'globalWorkflow'
} as const;
export type WorkItemTypeTemplateUpdateModelTemplateTypeEnum = typeof WorkItemTypeTemplateUpdateModelTemplateTypeEnum[keyof typeof WorkItemTypeTemplateUpdateModelTemplateTypeEnum];


/**
 * Check if a given object implements the WorkItemTypeTemplateUpdateModel interface.
 */
export function instanceOfWorkItemTypeTemplateUpdateModel(value: object): value is WorkItemTypeTemplateUpdateModel {
    return true;
}

export function WorkItemTypeTemplateUpdateModelFromJSON(json: any): WorkItemTypeTemplateUpdateModel {
    return WorkItemTypeTemplateUpdateModelFromJSONTyped(json, false);
}

export function WorkItemTypeTemplateUpdateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemTypeTemplateUpdateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'actionType': json['actionType'] == null ? undefined : json['actionType'],
        'methodology': json['methodology'] == null ? undefined : json['methodology'],
        'template': json['template'] == null ? undefined : json['template'],
        'templateType': json['templateType'] == null ? undefined : json['templateType'],
    };
}

export function WorkItemTypeTemplateUpdateModelToJSON(json: any): WorkItemTypeTemplateUpdateModel {
    return WorkItemTypeTemplateUpdateModelToJSONTyped(json, false);
}

export function WorkItemTypeTemplateUpdateModelToJSONTyped(value?: WorkItemTypeTemplateUpdateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actionType': value['actionType'],
        'methodology': value['methodology'],
        'template': value['template'],
        'templateType': value['templateType'],
    };
}

