/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkItemReference } from './WorkItemReference';
import {
    WorkItemReferenceFromJSON,
    WorkItemReferenceFromJSONTyped,
    WorkItemReferenceToJSON,
    WorkItemReferenceToJSONTyped,
} from './WorkItemReference';

/**
 * A link between two work items.
 * @export
 * @interface WorkItemLink
 */
export interface WorkItemLink {
    /**
     * The type of link.
     * @type {string}
     * @memberof WorkItemLink
     */
    rel?: string;
    /**
     * 
     * @type {WorkItemReference}
     * @memberof WorkItemLink
     */
    source?: WorkItemReference;
    /**
     * 
     * @type {WorkItemReference}
     * @memberof WorkItemLink
     */
    target?: WorkItemReference;
}

/**
 * Check if a given object implements the WorkItemLink interface.
 */
export function instanceOfWorkItemLink(value: object): value is WorkItemLink {
    return true;
}

export function WorkItemLinkFromJSON(json: any): WorkItemLink {
    return WorkItemLinkFromJSONTyped(json, false);
}

export function WorkItemLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemLink {
    if (json == null) {
        return json;
    }
    return {
        
        'rel': json['rel'] == null ? undefined : json['rel'],
        'source': json['source'] == null ? undefined : WorkItemReferenceFromJSON(json['source']),
        'target': json['target'] == null ? undefined : WorkItemReferenceFromJSON(json['target']),
    };
}

export function WorkItemLinkToJSON(json: any): WorkItemLink {
    return WorkItemLinkToJSONTyped(json, false);
}

export function WorkItemLinkToJSONTyped(value?: WorkItemLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rel': value['rel'],
        'source': WorkItemReferenceToJSON(value['source']),
        'target': WorkItemReferenceToJSON(value['target']),
    };
}

