/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceLinks } from './ReferenceLinks';
import {
    ReferenceLinksFromJSON,
    ReferenceLinksFromJSONTyped,
    ReferenceLinksToJSON,
    ReferenceLinksToJSONTyped,
} from './ReferenceLinks';

/**
 * Represents the work item type relation type.
 * @export
 * @interface WorkItemRelationType
 */
export interface WorkItemRelationType {
    /**
     * The collection of relation type attributes.
     * @type {{ [key: string]: object; }}
     * @memberof WorkItemRelationType
     */
    attributes?: { [key: string]: object; };
    /**
     * The name.
     * @type {string}
     * @memberof WorkItemRelationType
     */
    name?: string;
    /**
     * The reference name.
     * @type {string}
     * @memberof WorkItemRelationType
     */
    referenceName?: string;
    /**
     * 
     * @type {ReferenceLinks}
     * @memberof WorkItemRelationType
     */
    links?: ReferenceLinks;
    /**
     * REST URL for the resource.
     * @type {string}
     * @memberof WorkItemRelationType
     */
    url?: string;
}

/**
 * Check if a given object implements the WorkItemRelationType interface.
 */
export function instanceOfWorkItemRelationType(value: object): value is WorkItemRelationType {
    return true;
}

export function WorkItemRelationTypeFromJSON(json: any): WorkItemRelationType {
    return WorkItemRelationTypeFromJSONTyped(json, false);
}

export function WorkItemRelationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemRelationType {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'name': json['name'] == null ? undefined : json['name'],
        'referenceName': json['referenceName'] == null ? undefined : json['referenceName'],
        'links': json['_links'] == null ? undefined : ReferenceLinksFromJSON(json['_links']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function WorkItemRelationTypeToJSON(json: any): WorkItemRelationType {
    return WorkItemRelationTypeToJSONTyped(json, false);
}

export function WorkItemRelationTypeToJSONTyped(value?: WorkItemRelationType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'],
        'name': value['name'],
        'referenceName': value['referenceName'],
        '_links': ReferenceLinksToJSON(value['links']),
        'url': value['url'],
    };
}

