/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkItemFieldReference } from './WorkItemFieldReference';
import {
    WorkItemFieldReferenceFromJSON,
    WorkItemFieldReferenceFromJSONTyped,
    WorkItemFieldReferenceToJSON,
    WorkItemFieldReferenceToJSONTyped,
} from './WorkItemFieldReference';

/**
 * Field instance of a work item type.
 * @export
 * @interface WorkItemTypeFieldInstance
 */
export interface WorkItemTypeFieldInstance {
    /**
     * The list of field allowed values.
     * @type {Array<string>}
     * @memberof WorkItemTypeFieldInstance
     */
    allowedValues?: Array<string>;
    /**
     * Represents the default value of the field.
     * @type {string}
     * @memberof WorkItemTypeFieldInstance
     */
    defaultValue?: string;
    /**
     * Indicates whether field value is always required.
     * @type {boolean}
     * @memberof WorkItemTypeFieldInstance
     */
    alwaysRequired?: boolean;
    /**
     * The list of dependent fields.
     * @type {Array<WorkItemFieldReference>}
     * @memberof WorkItemTypeFieldInstance
     */
    dependentFields?: Array<WorkItemFieldReference>;
    /**
     * Gets the help text for the field.
     * @type {string}
     * @memberof WorkItemTypeFieldInstance
     */
    helpText?: string;
    /**
     * The friendly name of the field.
     * @type {string}
     * @memberof WorkItemTypeFieldInstance
     */
    name?: string;
    /**
     * The reference name of the field.
     * @type {string}
     * @memberof WorkItemTypeFieldInstance
     */
    referenceName?: string;
    /**
     * The REST URL of the resource.
     * @type {string}
     * @memberof WorkItemTypeFieldInstance
     */
    url?: string;
}

/**
 * Check if a given object implements the WorkItemTypeFieldInstance interface.
 */
export function instanceOfWorkItemTypeFieldInstance(value: object): value is WorkItemTypeFieldInstance {
    return true;
}

export function WorkItemTypeFieldInstanceFromJSON(json: any): WorkItemTypeFieldInstance {
    return WorkItemTypeFieldInstanceFromJSONTyped(json, false);
}

export function WorkItemTypeFieldInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemTypeFieldInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedValues': json['allowedValues'] == null ? undefined : json['allowedValues'],
        'defaultValue': json['defaultValue'] == null ? undefined : json['defaultValue'],
        'alwaysRequired': json['alwaysRequired'] == null ? undefined : json['alwaysRequired'],
        'dependentFields': json['dependentFields'] == null ? undefined : ((json['dependentFields'] as Array<any>).map(WorkItemFieldReferenceFromJSON)),
        'helpText': json['helpText'] == null ? undefined : json['helpText'],
        'name': json['name'] == null ? undefined : json['name'],
        'referenceName': json['referenceName'] == null ? undefined : json['referenceName'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function WorkItemTypeFieldInstanceToJSON(json: any): WorkItemTypeFieldInstance {
    return WorkItemTypeFieldInstanceToJSONTyped(json, false);
}

export function WorkItemTypeFieldInstanceToJSONTyped(value?: WorkItemTypeFieldInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowedValues': value['allowedValues'],
        'defaultValue': value['defaultValue'],
        'alwaysRequired': value['alwaysRequired'],
        'dependentFields': value['dependentFields'] == null ? undefined : ((value['dependentFields'] as Array<any>).map(WorkItemFieldReferenceToJSON)),
        'helpText': value['helpText'],
        'name': value['name'],
        'referenceName': value['referenceName'],
        'url': value['url'],
    };
}

