/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A work artifact link describes an outbound artifact link type.
 * @export
 * @interface WorkArtifactLink
 */
export interface WorkArtifactLink {
    /**
     * Target artifact type.
     * @type {string}
     * @memberof WorkArtifactLink
     */
    artifactType?: string;
    /**
     * Outbound link type.
     * @type {string}
     * @memberof WorkArtifactLink
     */
    linkType?: string;
    /**
     * Target tool type.
     * @type {string}
     * @memberof WorkArtifactLink
     */
    toolType?: string;
}

/**
 * Check if a given object implements the WorkArtifactLink interface.
 */
export function instanceOfWorkArtifactLink(value: object): value is WorkArtifactLink {
    return true;
}

export function WorkArtifactLinkFromJSON(json: any): WorkArtifactLink {
    return WorkArtifactLinkFromJSONTyped(json, false);
}

export function WorkArtifactLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkArtifactLink {
    if (json == null) {
        return json;
    }
    return {
        
        'artifactType': json['artifactType'] == null ? undefined : json['artifactType'],
        'linkType': json['linkType'] == null ? undefined : json['linkType'],
        'toolType': json['toolType'] == null ? undefined : json['toolType'],
    };
}

export function WorkArtifactLinkToJSON(json: any): WorkArtifactLink {
    return WorkArtifactLinkToJSONTyped(json, false);
}

export function WorkArtifactLinkToJSONTyped(value?: WorkArtifactLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artifactType': value['artifactType'],
        'linkType': value['linkType'],
        'toolType': value['toolType'],
    };
}

