/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes an update to a work item field.
 * @export
 * @interface WorkItemFieldUpdate
 */
export interface WorkItemFieldUpdate {
    /**
     * The new value of the field.
     * @type {object}
     * @memberof WorkItemFieldUpdate
     */
    newValue?: object;
    /**
     * The old value of the field.
     * @type {object}
     * @memberof WorkItemFieldUpdate
     */
    oldValue?: object;
}

/**
 * Check if a given object implements the WorkItemFieldUpdate interface.
 */
export function instanceOfWorkItemFieldUpdate(value: object): value is WorkItemFieldUpdate {
    return true;
}

export function WorkItemFieldUpdateFromJSON(json: any): WorkItemFieldUpdate {
    return WorkItemFieldUpdateFromJSONTyped(json, false);
}

export function WorkItemFieldUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemFieldUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'newValue': json['newValue'] == null ? undefined : json['newValue'],
        'oldValue': json['oldValue'] == null ? undefined : json['oldValue'],
    };
}

export function WorkItemFieldUpdateToJSON(json: any): WorkItemFieldUpdate {
    return WorkItemFieldUpdateToJSONTyped(json, false);
}

export function WorkItemFieldUpdateToJSONTyped(value?: WorkItemFieldUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newValue': value['newValue'],
        'oldValue': value['oldValue'],
    };
}

