/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes a state transition in a work item.
 * @export
 * @interface WorkItemStateTransition
 */
export interface WorkItemStateTransition {
    /**
     * Gets a list of actions needed to transition to that state.
     * @type {Array<string>}
     * @memberof WorkItemStateTransition
     */
    actions?: Array<string>;
    /**
     * Name of the next state.
     * @type {string}
     * @memberof WorkItemStateTransition
     */
    to?: string;
}

/**
 * Check if a given object implements the WorkItemStateTransition interface.
 */
export function instanceOfWorkItemStateTransition(value: object): value is WorkItemStateTransition {
    return true;
}

export function WorkItemStateTransitionFromJSON(json: any): WorkItemStateTransition {
    return WorkItemStateTransitionFromJSONTyped(json, false);
}

export function WorkItemStateTransitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemStateTransition {
    if (json == null) {
        return json;
    }
    return {
        
        'actions': json['actions'] == null ? undefined : json['actions'],
        'to': json['to'] == null ? undefined : json['to'],
    };
}

export function WorkItemStateTransitionToJSON(json: any): WorkItemStateTransition {
    return WorkItemStateTransitionToJSONTyped(json, false);
}

export function WorkItemStateTransitionToJSONTyped(value?: WorkItemStateTransition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actions': value['actions'],
        'to': value['to'],
    };
}

