/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reference to a work item icon.
 * @export
 * @interface WorkItemIcon
 */
export interface WorkItemIcon {
    /**
     * The identifier of the icon.
     * @type {string}
     * @memberof WorkItemIcon
     */
    id?: string;
    /**
     * The REST URL of the resource.
     * @type {string}
     * @memberof WorkItemIcon
     */
    url?: string;
}

/**
 * Check if a given object implements the WorkItemIcon interface.
 */
export function instanceOfWorkItemIcon(value: object): value is WorkItemIcon {
    return true;
}

export function WorkItemIconFromJSON(json: any): WorkItemIcon {
    return WorkItemIconFromJSONTyped(json, false);
}

export function WorkItemIconFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemIcon {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function WorkItemIconToJSON(json: any): WorkItemIcon {
    return WorkItemIconToJSONTyped(json, false);
}

export function WorkItemIconToJSONTyped(value?: WorkItemIcon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
    };
}

