/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes a work item type template.
 * @export
 * @interface WorkItemTypeTemplate
 */
export interface WorkItemTypeTemplate {
    /**
     * XML template in string format.
     * @type {string}
     * @memberof WorkItemTypeTemplate
     */
    template?: string;
}

/**
 * Check if a given object implements the WorkItemTypeTemplate interface.
 */
export function instanceOfWorkItemTypeTemplate(value: object): value is WorkItemTypeTemplate {
    return true;
}

export function WorkItemTypeTemplateFromJSON(json: any): WorkItemTypeTemplate {
    return WorkItemTypeTemplateFromJSONTyped(json, false);
}

export function WorkItemTypeTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemTypeTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'template': json['template'] == null ? undefined : json['template'],
    };
}

export function WorkItemTypeTemplateToJSON(json: any): WorkItemTypeTemplate {
    return WorkItemTypeTemplateToJSONTyped(json, false);
}

export function WorkItemTypeTemplateToJSONTyped(value?: WorkItemTypeTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template': value['template'],
    };
}

