/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceLinks } from './ReferenceLinks';
import {
    ReferenceLinksFromJSON,
    ReferenceLinksFromJSONTyped,
    ReferenceLinksToJSON,
    ReferenceLinksToJSONTyped,
} from './ReferenceLinks';
import type { WorkItemComment } from './WorkItemComment';
import {
    WorkItemCommentFromJSON,
    WorkItemCommentFromJSONTyped,
    WorkItemCommentToJSON,
    WorkItemCommentToJSONTyped,
} from './WorkItemComment';

/**
 * Collection of comments.
 * @export
 * @interface WorkItemComments
 */
export interface WorkItemComments {
    /**
     * Comments collection.
     * @type {Array<WorkItemComment>}
     * @memberof WorkItemComments
     */
    comments?: Array<WorkItemComment>;
    /**
     * The count of comments.
     * @type {number}
     * @memberof WorkItemComments
     */
    count?: number;
    /**
     * Count of comments from the revision.
     * @type {number}
     * @memberof WorkItemComments
     */
    fromRevisionCount?: number;
    /**
     * Total count of comments.
     * @type {number}
     * @memberof WorkItemComments
     */
    totalCount?: number;
    /**
     * 
     * @type {ReferenceLinks}
     * @memberof WorkItemComments
     */
    links?: ReferenceLinks;
    /**
     * REST URL for the resource.
     * @type {string}
     * @memberof WorkItemComments
     */
    url?: string;
}

/**
 * Check if a given object implements the WorkItemComments interface.
 */
export function instanceOfWorkItemComments(value: object): value is WorkItemComments {
    return true;
}

export function WorkItemCommentsFromJSON(json: any): WorkItemComments {
    return WorkItemCommentsFromJSONTyped(json, false);
}

export function WorkItemCommentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemComments {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(WorkItemCommentFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
        'fromRevisionCount': json['fromRevisionCount'] == null ? undefined : json['fromRevisionCount'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'links': json['_links'] == null ? undefined : ReferenceLinksFromJSON(json['_links']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function WorkItemCommentsToJSON(json: any): WorkItemComments {
    return WorkItemCommentsToJSONTyped(json, false);
}

export function WorkItemCommentsToJSONTyped(value?: WorkItemComments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(WorkItemCommentToJSON)),
        'count': value['count'],
        'fromRevisionCount': value['fromRevisionCount'],
        'totalCount': value['totalCount'],
        '_links': ReferenceLinksToJSON(value['links']),
        'url': value['url'],
    };
}

