/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes a work item type's colors.
 * @export
 * @interface WorkItemTypeColor
 */
export interface WorkItemTypeColor {
    /**
     * Gets or sets the color of the primary.
     * @type {string}
     * @memberof WorkItemTypeColor
     */
    primaryColor?: string;
    /**
     * Gets or sets the color of the secondary.
     * @type {string}
     * @memberof WorkItemTypeColor
     */
    secondaryColor?: string;
    /**
     * The name of the work item type.
     * @type {string}
     * @memberof WorkItemTypeColor
     */
    workItemTypeName?: string;
}

/**
 * Check if a given object implements the WorkItemTypeColor interface.
 */
export function instanceOfWorkItemTypeColor(value: object): value is WorkItemTypeColor {
    return true;
}

export function WorkItemTypeColorFromJSON(json: any): WorkItemTypeColor {
    return WorkItemTypeColorFromJSONTyped(json, false);
}

export function WorkItemTypeColorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemTypeColor {
    if (json == null) {
        return json;
    }
    return {
        
        'primaryColor': json['primaryColor'] == null ? undefined : json['primaryColor'],
        'secondaryColor': json['secondaryColor'] == null ? undefined : json['secondaryColor'],
        'workItemTypeName': json['workItemTypeName'] == null ? undefined : json['workItemTypeName'],
    };
}

export function WorkItemTypeColorToJSON(json: any): WorkItemTypeColor {
    return WorkItemTypeColorToJSONTyped(json, false);
}

export function WorkItemTypeColorToJSONTyped(value?: WorkItemTypeColor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primaryColor': value['primaryColor'],
        'secondaryColor': value['secondaryColor'],
        'workItemTypeName': value['workItemTypeName'],
    };
}

