/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkItemFieldReference } from './WorkItemFieldReference';
import {
    WorkItemFieldReferenceFromJSON,
    WorkItemFieldReferenceFromJSONTyped,
    WorkItemFieldReferenceToJSON,
    WorkItemFieldReferenceToJSONTyped,
} from './WorkItemFieldReference';

/**
 * A sort column.
 * @export
 * @interface WorkItemQuerySortColumn
 */
export interface WorkItemQuerySortColumn {
    /**
     * The direction to sort by.
     * @type {boolean}
     * @memberof WorkItemQuerySortColumn
     */
    descending?: boolean;
    /**
     * 
     * @type {WorkItemFieldReference}
     * @memberof WorkItemQuerySortColumn
     */
    field?: WorkItemFieldReference;
}

/**
 * Check if a given object implements the WorkItemQuerySortColumn interface.
 */
export function instanceOfWorkItemQuerySortColumn(value: object): value is WorkItemQuerySortColumn {
    return true;
}

export function WorkItemQuerySortColumnFromJSON(json: any): WorkItemQuerySortColumn {
    return WorkItemQuerySortColumnFromJSONTyped(json, false);
}

export function WorkItemQuerySortColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemQuerySortColumn {
    if (json == null) {
        return json;
    }
    return {
        
        'descending': json['descending'] == null ? undefined : json['descending'],
        'field': json['field'] == null ? undefined : WorkItemFieldReferenceFromJSON(json['field']),
    };
}

export function WorkItemQuerySortColumnToJSON(json: any): WorkItemQuerySortColumn {
    return WorkItemQuerySortColumnToJSONTyped(json, false);
}

export function WorkItemQuerySortColumnToJSONTyped(value?: WorkItemQuerySortColumn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'descending': value['descending'],
        'field': WorkItemFieldReferenceToJSON(value['field']),
    };
}

