/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkItemTagDefinition
 */
export interface WorkItemTagDefinition {
    /**
     * 
     * @type {string}
     * @memberof WorkItemTagDefinition
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkItemTagDefinition
     */
    lastUpdated?: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkItemTagDefinition
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkItemTagDefinition
     */
    url?: string;
}

/**
 * Check if a given object implements the WorkItemTagDefinition interface.
 */
export function instanceOfWorkItemTagDefinition(value: object): value is WorkItemTagDefinition {
    return true;
}

export function WorkItemTagDefinitionFromJSON(json: any): WorkItemTagDefinition {
    return WorkItemTagDefinitionFromJSONTyped(json, false);
}

export function WorkItemTagDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemTagDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : (new Date(json['lastUpdated'])),
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function WorkItemTagDefinitionToJSON(json: any): WorkItemTagDefinition {
    return WorkItemTagDefinitionToJSONTyped(json, false);
}

export function WorkItemTagDefinitionToJSONTyped(value?: WorkItemTagDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lastUpdated': value['lastUpdated'] == null ? undefined : ((value['lastUpdated']).toISOString()),
        'name': value['name'],
        'url': value['url'],
    };
}

