/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceLinks } from './ReferenceLinks';
import {
    ReferenceLinksFromJSON,
    ReferenceLinksFromJSONTyped,
    ReferenceLinksToJSON,
    ReferenceLinksToJSONTyped,
} from './ReferenceLinks';
import type { WorkItemCommentVersionRef } from './WorkItemCommentVersionRef';
import {
    WorkItemCommentVersionRefFromJSON,
    WorkItemCommentVersionRefFromJSONTyped,
    WorkItemCommentVersionRefToJSON,
    WorkItemCommentVersionRefToJSONTyped,
} from './WorkItemCommentVersionRef';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * Describes a work item.
 * @export
 * @interface WorkItem
 */
export interface WorkItem {
    /**
     * 
     * @type {WorkItemCommentVersionRef}
     * @memberof WorkItem
     */
    commentVersionRef?: WorkItemCommentVersionRef;
    /**
     * Map of field and values for the work item.
     * @type {{ [key: string]: object; }}
     * @memberof WorkItem
     */
    fields?: { [key: string]: object; };
    /**
     * The work item ID.
     * @type {number}
     * @memberof WorkItem
     */
    id?: number;
    /**
     * Relations of the work item.
     * @type {Array<WorkItemRelation>}
     * @memberof WorkItem
     */
    relations?: Array<WorkItemRelation>;
    /**
     * Revision number of the work item.
     * @type {number}
     * @memberof WorkItem
     */
    rev?: number;
    /**
     * 
     * @type {ReferenceLinks}
     * @memberof WorkItem
     */
    links?: ReferenceLinks;
    /**
     * REST URL for the resource.
     * @type {string}
     * @memberof WorkItem
     */
    url?: string;
}

/**
 * Check if a given object implements the WorkItem interface.
 */
export function instanceOfWorkItem(value: object): value is WorkItem {
    return true;
}

export function WorkItemFromJSON(json: any): WorkItem {
    return WorkItemFromJSONTyped(json, false);
}

export function WorkItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItem {
    if (json == null) {
        return json;
    }
    return {
        
        'commentVersionRef': json['commentVersionRef'] == null ? undefined : WorkItemCommentVersionRefFromJSON(json['commentVersionRef']),
        'fields': json['fields'] == null ? undefined : json['fields'],
        'id': json['id'] == null ? undefined : json['id'],
        'relations': json['relations'] == null ? undefined : ((json['relations'] as Array<any>).map(LinkFromJSON)),
        'rev': json['rev'] == null ? undefined : json['rev'],
        'links': json['_links'] == null ? undefined : ReferenceLinksFromJSON(json['_links']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function WorkItemToJSON(json: any): WorkItem {
    return WorkItemToJSONTyped(json, false);
}

export function WorkItemToJSONTyped(value?: WorkItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commentVersionRef': WorkItemCommentVersionRefToJSON(value['commentVersionRef']),
        'fields': value['fields'],
        'id': value['id'],
        'relations': value['relations'] == null ? undefined : ((value['relations'] as Array<any>).map(LinkToJSON)),
        'rev': value['rev'],
        '_links': ReferenceLinksToJSON(value['links']),
        'url': value['url'],
    };
}

