/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountRecentActivityWorkItemModel2,
} from '../models/index';
import {
    AccountRecentActivityWorkItemModel2FromJSON,
    AccountRecentActivityWorkItemModel2ToJSON,
} from '../models/index';

export interface AccountMyWorkRecentActivityListRequest {
    organization: string;
    apiVersion: string;
}

/**
 * 
 */
export class AccountMyWorkRecentActivityApi extends runtime.BaseAPI {

    /**
     * Gets recent work item activities
     */
    async accountMyWorkRecentActivityListRaw(requestParameters: AccountMyWorkRecentActivityListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AccountRecentActivityWorkItemModel2>>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling accountMyWorkRecentActivityList().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling accountMyWorkRecentActivityList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work"]);
        }

        const response = await this.request({
            path: `/{organization}/_apis/work/accountmyworkrecentactivity`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountRecentActivityWorkItemModel2FromJSON));
    }

    /**
     * Gets recent work item activities
     */
    async accountMyWorkRecentActivityList(requestParameters: AccountMyWorkRecentActivityListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AccountRecentActivityWorkItemModel2>> {
        const response = await this.accountMyWorkRecentActivityListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
