/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommentReaction,
} from '../models/index';
import {
    CommentReactionFromJSON,
    CommentReactionToJSON,
} from '../models/index';

export interface CommentsReactionsCreateRequest {
    organization: string;
    project: string;
    workItemId: number;
    commentId: number;
    reactionType: CommentsReactionsCreateReactionTypeEnum;
    apiVersion: string;
}

export interface CommentsReactionsDeleteRequest {
    organization: string;
    project: string;
    workItemId: number;
    commentId: number;
    reactionType: CommentsReactionsDeleteReactionTypeEnum;
    apiVersion: string;
}

export interface CommentsReactionsListRequest {
    organization: string;
    project: string;
    workItemId: number;
    commentId: number;
    apiVersion: string;
}

/**
 * 
 */
export class CommentsReactionsApi extends runtime.BaseAPI {

    /**
     * Adds a new reaction to a comment.
     */
    async commentsReactionsCreateRaw(requestParameters: CommentsReactionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentReaction>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling commentsReactionsCreate().'
            );
        }

        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling commentsReactionsCreate().'
            );
        }

        if (requestParameters['workItemId'] == null) {
            throw new runtime.RequiredError(
                'workItemId',
                'Required parameter "workItemId" was null or undefined when calling commentsReactionsCreate().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling commentsReactionsCreate().'
            );
        }

        if (requestParameters['reactionType'] == null) {
            throw new runtime.RequiredError(
                'reactionType',
                'Required parameter "reactionType" was null or undefined when calling commentsReactionsCreate().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling commentsReactionsCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work_write"]);
        }

        const response = await this.request({
            path: `/{organization}/{project}/_apis/wit/workItems/{workItemId}/comments/{commentId}/reactions/{reactionType}`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))).replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project']))).replace(`{${"workItemId"}}`, encodeURIComponent(String(requestParameters['workItemId']))).replace(`{${"commentId"}}`, encodeURIComponent(String(requestParameters['commentId']))).replace(`{${"reactionType"}}`, encodeURIComponent(String(requestParameters['reactionType']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentReactionFromJSON(jsonValue));
    }

    /**
     * Adds a new reaction to a comment.
     */
    async commentsReactionsCreate(requestParameters: CommentsReactionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentReaction> {
        const response = await this.commentsReactionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an existing reaction on a comment.
     */
    async commentsReactionsDeleteRaw(requestParameters: CommentsReactionsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentReaction>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling commentsReactionsDelete().'
            );
        }

        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling commentsReactionsDelete().'
            );
        }

        if (requestParameters['workItemId'] == null) {
            throw new runtime.RequiredError(
                'workItemId',
                'Required parameter "workItemId" was null or undefined when calling commentsReactionsDelete().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling commentsReactionsDelete().'
            );
        }

        if (requestParameters['reactionType'] == null) {
            throw new runtime.RequiredError(
                'reactionType',
                'Required parameter "reactionType" was null or undefined when calling commentsReactionsDelete().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling commentsReactionsDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work_write"]);
        }

        const response = await this.request({
            path: `/{organization}/{project}/_apis/wit/workItems/{workItemId}/comments/{commentId}/reactions/{reactionType}`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))).replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project']))).replace(`{${"workItemId"}}`, encodeURIComponent(String(requestParameters['workItemId']))).replace(`{${"commentId"}}`, encodeURIComponent(String(requestParameters['commentId']))).replace(`{${"reactionType"}}`, encodeURIComponent(String(requestParameters['reactionType']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentReactionFromJSON(jsonValue));
    }

    /**
     * Deletes an existing reaction on a comment.
     */
    async commentsReactionsDelete(requestParameters: CommentsReactionsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentReaction> {
        const response = await this.commentsReactionsDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets reactions of a comment.
     */
    async commentsReactionsListRaw(requestParameters: CommentsReactionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommentReaction>>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling commentsReactionsList().'
            );
        }

        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling commentsReactionsList().'
            );
        }

        if (requestParameters['workItemId'] == null) {
            throw new runtime.RequiredError(
                'workItemId',
                'Required parameter "workItemId" was null or undefined when calling commentsReactionsList().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling commentsReactionsList().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling commentsReactionsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work"]);
        }

        const response = await this.request({
            path: `/{organization}/{project}/_apis/wit/workItems/{workItemId}/comments/{commentId}/reactions`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))).replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project']))).replace(`{${"workItemId"}}`, encodeURIComponent(String(requestParameters['workItemId']))).replace(`{${"commentId"}}`, encodeURIComponent(String(requestParameters['commentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommentReactionFromJSON));
    }

    /**
     * Gets reactions of a comment.
     */
    async commentsReactionsList(requestParameters: CommentsReactionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommentReaction>> {
        const response = await this.commentsReactionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CommentsReactionsCreateReactionTypeEnum = {
    Like: 'like',
    Dislike: 'dislike',
    Heart: 'heart',
    Hooray: 'hooray',
    Smile: 'smile',
    Confused: 'confused'
} as const;
export type CommentsReactionsCreateReactionTypeEnum = typeof CommentsReactionsCreateReactionTypeEnum[keyof typeof CommentsReactionsCreateReactionTypeEnum];
/**
 * @export
 */
export const CommentsReactionsDeleteReactionTypeEnum = {
    Like: 'like',
    Dislike: 'dislike',
    Heart: 'heart',
    Hooray: 'hooray',
    Smile: 'smile',
    Confused: 'confused'
} as const;
export type CommentsReactionsDeleteReactionTypeEnum = typeof CommentsReactionsDeleteReactionTypeEnum[keyof typeof CommentsReactionsDeleteReactionTypeEnum];
