/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProcessIdModel,
  ProcessMigrationResultModel,
} from '../models/index';
import {
    ProcessIdModelFromJSON,
    ProcessIdModelToJSON,
    ProcessMigrationResultModelFromJSON,
    ProcessMigrationResultModelToJSON,
} from '../models/index';

export interface ProjectProcessMigrationMigrateProjectsProcessRequest {
    organization: string;
    project: string;
    apiVersion: string;
    body: ProcessIdModel;
}

/**
 * 
 */
export class ProjectProcessMigrationApi extends runtime.BaseAPI {

    /**
     * Migrates a project to a different process within the same OOB type. For example, you can only migrate a project from agile/custom-agile to agile/custom-agile.
     */
    async projectProcessMigrationMigrateProjectsProcessRaw(requestParameters: ProjectProcessMigrationMigrateProjectsProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessMigrationResultModel>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling projectProcessMigrationMigrateProjectsProcess().'
            );
        }

        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling projectProcessMigrationMigrateProjectsProcess().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling projectProcessMigrationMigrateProjectsProcess().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling projectProcessMigrationMigrateProjectsProcess().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work_write"]);
        }

        const response = await this.request({
            path: `/{organization}/{project}/_apis/wit/projectprocessmigration`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))).replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProcessIdModelToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessMigrationResultModelFromJSON(jsonValue));
    }

    /**
     * Migrates a project to a different process within the same OOB type. For example, you can only migrate a project from agile/custom-agile to agile/custom-agile.
     */
    async projectProcessMigrationMigrateProjectsProcess(requestParameters: ProjectProcessMigrationMigrateProjectsProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessMigrationResultModel> {
        const response = await this.projectProcessMigrationMigrateProjectsProcessRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
