/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReportingWorkItemRevisionsFilter,
  StreamedBatch,
} from '../models/index';
import {
    ReportingWorkItemRevisionsFilterFromJSON,
    ReportingWorkItemRevisionsFilterToJSON,
    StreamedBatchFromJSON,
    StreamedBatchToJSON,
} from '../models/index';

export interface ReportingWorkItemRevisionsReadReportingRevisionsGetRequest {
    organization: string;
    project: string;
    apiVersion: string;
    fields?: string;
    types?: string;
    continuationToken?: string;
    startDateTime?: Date;
    includeIdentityRef?: boolean;
    includeDeleted?: boolean;
    includeTagRef?: boolean;
    includeLatestOnly?: boolean;
    $expand?: ReportingWorkItemRevisionsReadReportingRevisionsGetExpandEnum;
    includeDiscussionChangesOnly?: boolean;
    $maxPageSize?: number;
}

export interface ReportingWorkItemRevisionsReadReportingRevisionsPostRequest {
    organization: string;
    project: string;
    apiVersion: string;
    body: ReportingWorkItemRevisionsFilter;
    continuationToken?: string;
    startDateTime?: Date;
    $expand?: ReportingWorkItemRevisionsReadReportingRevisionsPostExpandEnum;
}

/**
 * 
 */
export class ReportingWorkItemRevisionsApi extends runtime.BaseAPI {

    /**
     * Get a batch of work item revisions with the option of including deleted items
     */
    async reportingWorkItemRevisionsReadReportingRevisionsGetRaw(requestParameters: ReportingWorkItemRevisionsReadReportingRevisionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreamedBatch>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling reportingWorkItemRevisionsReadReportingRevisionsGet().'
            );
        }

        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling reportingWorkItemRevisionsReadReportingRevisionsGet().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling reportingWorkItemRevisionsReadReportingRevisionsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['types'] != null) {
            queryParameters['types'] = requestParameters['types'];
        }

        if (requestParameters['continuationToken'] != null) {
            queryParameters['continuationToken'] = requestParameters['continuationToken'];
        }

        if (requestParameters['startDateTime'] != null) {
            queryParameters['startDateTime'] = (requestParameters['startDateTime'] as any).toISOString();
        }

        if (requestParameters['includeIdentityRef'] != null) {
            queryParameters['includeIdentityRef'] = requestParameters['includeIdentityRef'];
        }

        if (requestParameters['includeDeleted'] != null) {
            queryParameters['includeDeleted'] = requestParameters['includeDeleted'];
        }

        if (requestParameters['includeTagRef'] != null) {
            queryParameters['includeTagRef'] = requestParameters['includeTagRef'];
        }

        if (requestParameters['includeLatestOnly'] != null) {
            queryParameters['includeLatestOnly'] = requestParameters['includeLatestOnly'];
        }

        if (requestParameters['$expand'] != null) {
            queryParameters['$expand'] = requestParameters['$expand'];
        }

        if (requestParameters['includeDiscussionChangesOnly'] != null) {
            queryParameters['includeDiscussionChangesOnly'] = requestParameters['includeDiscussionChangesOnly'];
        }

        if (requestParameters['$maxPageSize'] != null) {
            queryParameters['$maxPageSize'] = requestParameters['$maxPageSize'];
        }

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work"]);
        }

        const response = await this.request({
            path: `/{organization}/{project}/_apis/wit/reporting/workitemrevisions`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))).replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreamedBatchFromJSON(jsonValue));
    }

    /**
     * Get a batch of work item revisions with the option of including deleted items
     */
    async reportingWorkItemRevisionsReadReportingRevisionsGet(requestParameters: ReportingWorkItemRevisionsReadReportingRevisionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreamedBatch> {
        const response = await this.reportingWorkItemRevisionsReadReportingRevisionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a batch of work item revisions. This request may be used if your list of fields is large enough that it may run the URL over the length limit.
     */
    async reportingWorkItemRevisionsReadReportingRevisionsPostRaw(requestParameters: ReportingWorkItemRevisionsReadReportingRevisionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreamedBatch>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling reportingWorkItemRevisionsReadReportingRevisionsPost().'
            );
        }

        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling reportingWorkItemRevisionsReadReportingRevisionsPost().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling reportingWorkItemRevisionsReadReportingRevisionsPost().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling reportingWorkItemRevisionsReadReportingRevisionsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['continuationToken'] != null) {
            queryParameters['continuationToken'] = requestParameters['continuationToken'];
        }

        if (requestParameters['startDateTime'] != null) {
            queryParameters['startDateTime'] = (requestParameters['startDateTime'] as any).toISOString();
        }

        if (requestParameters['$expand'] != null) {
            queryParameters['$expand'] = requestParameters['$expand'];
        }

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work"]);
        }

        const response = await this.request({
            path: `/{organization}/{project}/_apis/wit/reporting/workitemrevisions`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))).replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReportingWorkItemRevisionsFilterToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreamedBatchFromJSON(jsonValue));
    }

    /**
     * Get a batch of work item revisions. This request may be used if your list of fields is large enough that it may run the URL over the length limit.
     */
    async reportingWorkItemRevisionsReadReportingRevisionsPost(requestParameters: ReportingWorkItemRevisionsReadReportingRevisionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreamedBatch> {
        const response = await this.reportingWorkItemRevisionsReadReportingRevisionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ReportingWorkItemRevisionsReadReportingRevisionsGetExpandEnum = {
    None: 'none',
    Fields: 'fields'
} as const;
export type ReportingWorkItemRevisionsReadReportingRevisionsGetExpandEnum = typeof ReportingWorkItemRevisionsReadReportingRevisionsGetExpandEnum[keyof typeof ReportingWorkItemRevisionsReadReportingRevisionsGetExpandEnum];
/**
 * @export
 */
export const ReportingWorkItemRevisionsReadReportingRevisionsPostExpandEnum = {
    None: 'none',
    Fields: 'fields'
} as const;
export type ReportingWorkItemRevisionsReadReportingRevisionsPostExpandEnum = typeof ReportingWorkItemRevisionsReadReportingRevisionsPostExpandEnum[keyof typeof ReportingWorkItemRevisionsReadReportingRevisionsPostExpandEnum];
