/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WorkItemTypeCategory,
} from '../models/index';
import {
    WorkItemTypeCategoryFromJSON,
    WorkItemTypeCategoryToJSON,
} from '../models/index';

export interface WorkItemTypeCategoriesGetRequest {
    organization: string;
    project: string;
    category: string;
    apiVersion: string;
}

export interface WorkItemTypeCategoriesListRequest {
    organization: string;
    project: string;
    apiVersion: string;
}

/**
 * 
 */
export class WorkItemTypeCategoriesApi extends runtime.BaseAPI {

    /**
     * Get specific work item type category by name.
     */
    async workItemTypeCategoriesGetRaw(requestParameters: WorkItemTypeCategoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkItemTypeCategory>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling workItemTypeCategoriesGet().'
            );
        }

        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling workItemTypeCategoriesGet().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling workItemTypeCategoriesGet().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling workItemTypeCategoriesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work"]);
        }

        const response = await this.request({
            path: `/{organization}/{project}/_apis/wit/workitemtypecategories/{category}`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))).replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkItemTypeCategoryFromJSON(jsonValue));
    }

    /**
     * Get specific work item type category by name.
     */
    async workItemTypeCategoriesGet(requestParameters: WorkItemTypeCategoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkItemTypeCategory> {
        const response = await this.workItemTypeCategoriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all work item type categories.
     */
    async workItemTypeCategoriesListRaw(requestParameters: WorkItemTypeCategoriesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkItemTypeCategory>>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling workItemTypeCategoriesList().'
            );
        }

        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling workItemTypeCategoriesList().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling workItemTypeCategoriesList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work"]);
        }

        const response = await this.request({
            path: `/{organization}/{project}/_apis/wit/workitemtypecategories`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))).replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkItemTypeCategoryFromJSON));
    }

    /**
     * Get all work item type categories.
     */
    async workItemTypeCategoriesList(requestParameters: WorkItemTypeCategoriesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkItemTypeCategory>> {
        const response = await this.workItemTypeCategoriesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
