/* tslint:disable */
/* eslint-disable */
/**
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WorkItemStateColor,
} from '../models/index';
import {
    WorkItemStateColorFromJSON,
    WorkItemStateColorToJSON,
} from '../models/index';

export interface WorkItemTypeStatesListRequest {
    organization: string;
    project: string;
    type: string;
    apiVersion: string;
}

/**
 * 
 */
export class WorkItemTypeStatesApi extends runtime.BaseAPI {

    /**
     * Returns the state names and colors for a work item type.
     */
    async workItemTypeStatesListRaw(requestParameters: WorkItemTypeStatesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkItemStateColor>>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling workItemTypeStatesList().'
            );
        }

        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling workItemTypeStatesList().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling workItemTypeStatesList().'
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling workItemTypeStatesList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["vso.work"]);
        }

        const response = await this.request({
            path: `/{organization}/{project}/_apis/wit/workitemtypes/{type}/states`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters['organization']))).replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project']))).replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkItemStateColorFromJSON));
    }

    /**
     * Returns the state names and colors for a work item type.
     */
    async workItemTypeStatesList(requestParameters: WorkItemTypeStatesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkItemStateColor>> {
        const response = await this.workItemTypeStatesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
